spring:
  application:
    name: payment-service
  webflux:
    base-path: /api
  resilience4j:
    circuitbreaker:
      configs:
        paymentEventCircuitBreaker:
          registerHealthIndicator: true
          slidingWindowSize: 10
          minimumNumberOfCalls: 5
          failureRateThreshold: 50
          waitDurationInOpenState: 10000
          automaticTransitionFromOpenToHalfOpenEnabled: true
      instances:
        paymentEvent:
          baseConfig: paymentEventCircuitBreaker
    retry:
      configs:
        paymentEventRetry:
          maxAttempts: 3
          waitDuration: PT1S
      instances:
        paymentEvent:
          config: paymentEventRetry
    bulkhead:
      configs:
        paymentEventBulkhead:
          maxConcurrentCalls: 10
          waitDurationInQueue: PT1S
      instances:
        paymentEvent:
          config: paymentEventBulkhead